[[collection]]
type = "card"
title = "Seimbang.in"
link = "https://github.com/seimbang-in"
content = "A smart money management app powered by AI and OCR to help Indonesians build better financial habits with personalized insights."
tags = ["mobile-app", "ai", "bangkit-academy"]

[[collection]]
type = "card"
title = "Jogjatour"
link = "https://github.com/shandikadav/jogjatour_app"
content = "A tourism app that showcases Yogyakarta's attractions to students, travelers, and locals, supporting exploration and local businesses."
tags = ["mobile-app", "flutter"]

[[collection]]
type = "card"
title = "e-Resource"
link = "https://github.com/shandikadav/eresource_app.git"
content = "A mobile library app built with Flutter to enhance access to Amikom's Resource Center, developed for an inter-campus competition."
tags = ["mobile-app", "flutter"]
