[[collection]]
type = "art_simple"
title = "Steins Gate"
img = "https://cdn.myanimelist.net/images/anime/1935/127974.jpg"

[[collection]]
type = "art_simple"
title = "Mushoku Tensei"
img = "https://cdn.myanimelist.net/images/anime/1530/117776.jpg"